version: '3.1'
services:
  mysql:
    hostname: mysql
    platform: linux/x86_64
    image: mysql:8.0.23
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - ksp-network
    expose:
      - "3306"
    ports:
      - "13306:3306"
  adminer:
    hostname: mysql
    platform: linux/x86_64
    image: adminer
    restart: always
    depends_on:
      - "mysql"
    networks:
      - ksp-network
    expose:
      - "8080"
    ports:
      - "18080:8080"
  app:
    hostname: ksp-api
    platform: linux/x86_64
    image: elkhanib/ksp:1.0.0
    restart: always
    depends_on:
      - "mysql"
    networks:
      - ksp-network
    ports:
      - "8081:8081"
volumes:
  db_data:
networks:
  ksp-network:
    driver: bridge